src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <description>Email address of patient</description>
        <inlineHelpText>What is your email address?</inlineHelpText>
        <label>Email</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Center_Information__c.object
<CustomObject>
    <fields>
        <fullName>CAdmin__c</fullName>
        <label>CAdmin</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CID__c</fullName>
        <label>CID</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Calendar_Name__c</fullName>
        <description>Short version of center name to display in the calendar</description>
        <label>Calendar Name</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Confirmation_Email_Address__c</fullName>
        <description>The email address that will receive a confirmation message whenever someone gets scheduled for a consultation at this center. Mainly used with Network Centers</description>
        <label>Confirmation Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Directions__c</fullName>
        <label>Directions</label>
        <length>500</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Doctor_1_Type__c</fullName>
        <label>Doctor 1 - Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Consult Dr</fullName>
                </value>
                <value>
                    <fullName>Expert Practitioner</fullName>
                </value>
                <value>
                    <fullName>General Dentist</fullName>
                </value>
                <value>
                    <fullName>OS</fullName>
                </value>
                <value>
                    <fullName>Pros</fullName>
                </value>
                <value>
                    <fullName>Pros Trained</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Doctor_1__c</fullName>
        <label>Doctor 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Doctor_2_Type__c</fullName>
        <label>Doctor 2 - Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Consult Dr</fullName>
                </value>
                <value>
                    <fullName>Expert Practitioner</fullName>
                </value>
                <value>
                    <fullName>General Dentist</fullName>
                </value>
                <value>
                    <fullName>OS</fullName>
                </value>
                <value>
                    <fullName>Pros</fullName>
                </value>
                <value>
                    <fullName>Pros Trained</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Doctor_2__c</fullName>
        <label>Doctor 2</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Location__c</fullName>
        <label>Location</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Market__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Center</relationshipLabel>
        <relationshipName>Center_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Market__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Market</label>
        <referenceTo>Market__c</referenceTo>
        <relationshipLabel>Center Information (Sales Market)</relationshipLabel>
        <relationshipName>Center_Information1</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Send_Confirmation_Email__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Controls whether we try to send an email when someone schedules a consultation at this location. This is mainly intended to be used for network centers</description>
        <label>Send Confirmation Email</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>District of Columbia</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Guam</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Street_1__c</fullName>
        <label>Street 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Main</fullName>
                </value>
                <value>
                    <fullName>Mini</fullName>
                </value>
                <value>
                    <fullName>Satellite</fullName>
                </value>
                <value>
                    <fullName>Affiliate</fullName>
                </value>
                <value>
                    <fullName>Network Center</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Center Information</label>
    <nameField>
        <label>Center Information Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Center Information</pluralLabel>
    <recordTypes>
        <fullName>Center</fullName>
        <active>true</active>
        <description>Captures Center Information</description>
        <label>Center</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Dental_Practice__c.object
<CustomObject>
    <description>A table to store one record for each unique dental practice we will be looking at for the referral program</description>
    <fields>
        <fullName>Center_Information__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Indicates the center this practice will be used with for referral purposes</description>
        <label>Center Information</label>
        <referenceTo>Center_Information__c</referenceTo>
        <relationshipLabel>Dental Practices</relationshipLabel>
        <relationshipName>Dental_Practices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <description>City the practice is located in</description>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Display_to_Vendor__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Display to Vendor</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PSA_Contract_Completed__c</fullName>
        <defaultValue>false</defaultValue>
        <label>PSA Contract Completed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Office Phone</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Postal_Code__c</fullName>
        <label>Postal Code</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Practice_Website__c</fullName>
        <label>Practice Website</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Primary_Contact_Email__c</fullName>
        <label>Primary Contact Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Primary_Contact_Name__c</fullName>
        <label>Primary Contact Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Refer_to_this_practice__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Indicates if our Compliance dept has approved these GP&apos;s for the PP program</description>
        <label>Approved by Compliance</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>State_Province__c</fullName>
        <label>State/Province</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street__c</fullName>
        <label>Street</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <label>Dental Practice</label>
    <nameField>
        <label>Dental Practice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dental Practices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Practice_Doctor__c.object
<CustomObject>
    <description>List of external doctors we receive and give referral patients to for the referral program (aka Practice Privileges).</description>
    <fields>
        <fullName>Dental_Practice__c</fullName>
        <label>Dental Practice</label>
        <referenceTo>Dental_Practice__c</referenceTo>
        <relationshipLabel>Practice Doctors</relationshipLabel>
        <relationshipName>Practice_Doctors</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <reparentableMasterDetail>true</reparentableMasterDetail>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <length>120</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone__c</fullName>
        <label>Phone</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Practice Doctor</label>
    <nameField>
        <displayFormat>DI-{0}</displayFormat>
        <label>Doctors ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Practice Doctors</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Referral_Out__c.object
<CustomObject>
    <description>A table that tracks the referrals out of our system on patients.</description>
    <fields>
        <fullName>Dental_Practice__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>The practice the patient was referred to.</description>
        <label>Dental Practice</label>
        <referenceTo>Dental_Practice__c</referenceTo>
        <relationshipLabel>Referrals Out</relationshipLabel>
        <relationshipName>Referrals_Out</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Referral Out</label>
    <nameField>
        <displayFormat>REF-{00000}</displayFormat>
        <label>Referral Out Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Referrals Out</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Dental_Practice__c</fullName>
        <formula>Contact.Account.Dental_Practice_Partner__c</formula>
        <label>Dental Practice</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Practice_Privileges_Provider__c</fullName>
        <label>Practice Privileges Provider</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>ClearViewTV</fullName>
                </value>
                <value>
                    <fullName>ClearTrain</fullName>
                </value>
                <value>
                    <fullName>ClearWeb</fullName>
                </value>
                <value>
                    <fullName>ClearVantage</fullName>
                </value>
                <value>
                    <fullName>ClearConnect</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/test_portal_referral_out.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 * 
 *  Major Code Coverage
 *  portal_referral_out  95%
 *
 */
@isTest
private class test_portal_referral_out {
static Center_Information__c test_center; 
  static Dental_Practice__c dp; 
  static User my_test_user;
  static User my_portal_test_user;
  
  private static void init() {
    Market__c m = new Market__c(name = 'test Market');
    insert m;
    test_center = new Center_Information__c(Name = 'Testing Center', Street_1__c = 'test', city__c = 'Denver', state__c = 'Colorado',
      directions__c = 'take a left,  straight on till morning', zip_code__c = '80012', market__c = m.id, sales_market__c = m.id, 
      cid__c = '1', location__c = 'loc', type__c = 'Main', doctor_1__c = 'test doc', doctor_2__c = 'test doc 2', 
      doctor_1_type__c = 'Pros', doctor_2_type__c = 'OS', cadmin__c = '1', latlong__Longitude__s = 32.368295, latlong__Latitude__s = 29.78233, calendar_name__c = 'Test Center',
      send_confirmation_email__c = true, confirmation_email_address__c = 'cmcdowell@clearchoice.com');
    insert test_center;
    
    
    Profile p = [select id from Profile where name = 'System Administrator'];       
    my_test_user = new User(profileid = p.id, email = 'testu@clearchoice.com', emailencodingkey = 'UTF-8',
        alias = 'testu', lastname = 'TestUser', localesidkey='en_US', country='United States', username='testu@clearchoice.com',
        timezonesidkey = 'America/Denver', languagelocalekey = 'en_US', Practice_Privileges_Provider__c='clearviewtv');
    insert my_test_user;
    dp = new Dental_Practice__c(name='Test Practice',primary_contact_name__c = 'Pcontact', Street__c = '111 Test Street', City__c = 'Colorado Springs',refer_to_this_practice__c = true, display_to_vendor__c = true,
        PSA_Contract_Completed__c = true, State_Province__c = 'CO', center_information__c = test_center.id, Postal_code__c = '91112', practice_website__c = 'www.test.com', phone__c = '5555555555', primary_contact_email__c = 'na@test.com', practice_management_software__c = 'Dentrix');
    insert dp;
    Practice_Doctor__c pd = new Practice_Doctor__c(first_name__c = 'Test', last_name__c = 'Doctor', Dental_practice__c = dp.id, email__c = 'test@clearchoice.com',phone__c = '1112223333');
    insert pd; 
    
    String rid = [Select id From RecordType where SobjectType = 'Account' and Name = 'Doctor Referral Account'].id;
    String pprid = [Select id From RecordType where SobjectType = 'Account' and Name = 'Prospective Patients'].id;
    
    //create a few accounts and leads to work with
    List<Lead> test_leads = new List<Lead> {new Lead(Center__c = test_center.id, Inbound_Call__c = 'Dental Inquiry', Trigger_Referral_Source__c = 'TV', 
        Call_Center_Agent__c = userinfo.getuserid(), LastName = 'Patient', FirstName = 'Test', Gender__c = 'Male',
        Call_Result__c = 'Not Scheduled', Phone = '7193321582', OBJECTION__c = 'Hung Up',email = 'cm@clearchoice.com', work__c = '719-555-5555', referral_office__c = dp.id),
      new Lead(Center__c = test_center.id, Inbound_Call__c = 'Dental Inquiry', Trigger_Referral_Source__c = 'TV', 
        Call_Center_Agent__c = userinfo.getuserid(), LastName = 'Patient', FirstName = 'NoOffice', Gender__c = 'Male',
        Call_Result__c = 'Not Scheduled', Phone = '7193321582', OBJECTION__c = 'Hung Up',email = 'cm@clearchoice.com', work__c = '719-555-5555', referral_office__c = dp.id)};
    insert test_leads;
    List<Referral_Out__c> rout_list = new List<Referral_Out__c> {
      new Referral_out__c(lead__c = test_leads[0].id, Dental_Practice__c = dp.id, preferred_callback_time__c = 'Evenings', Procedure_Interested_In__c = 'Hygiene', Referral_Notes__c = 'Test Notes'),
      new Referral_out__c(lead__c = test_leads[1].id, Dental_Practice__c = dp.id, preferred_callback_time__c = 'Morning', Procedure_Interested_In__c = 'Dentures', Referral_Notes__c = 'Test Notes')
    };
    insert rout_list;
       
    Account test_account = new Account(Name = 'Test Account2', Center__c = test_center.id, RecordTypeId = rid,dental_practice_partner__c = dp.id);
    insert test_account;
    Contact test_contact = new Contact(accountid = test_account.id, firstname = 'partner', lastname = 'portal test2');
    insert test_contact;
    p = [select id from Profile where name = 'Dental Practice Partner'];                  
    my_portal_test_user = new User(profileid = p.id, email = 'testportal@clearchoice.com', emailencodingkey = 'UTF-8',
        alias = 'tpor', lastname = 'TestPortal2', localesidkey='en_US', country='United States', username='testportal@clearchoice.com',
        timezonesidkey = 'America/Denver', languagelocalekey = 'en_US',  contactid = test_contact.id);
    insert my_portal_test_user;                
  }
  
  static testMethod void test_Referral_Out() {
    init();    
    test.startTest();
    
    PageReference pageref = new PageReference('/apex/portal_home');
    Test.setCurrentPage(pageref);
    portal_referral_out ctrl = new portal_referral_out();
    pageRef.getParameters().put('pid',null);
    ctrl = new portal_referral_out();
    pageRef.getParameters().put('pid','All');
    ctrl = new portal_referral_out();
    
    ctrl.getreferral_list_size();
    for(portal_referral_out.referral_out ro : ctrl.getpaged_referrals()) {
      ro.getreferral_practice();
      ro.getreferral_name();
      ro.getreferral_phone();
      ro.getreferral_email();
      ro.getreferral_street();
      ro.getreferral_state();
      ro.getreferral_city();
      ro.getreferral_link();
      ro.getreferral_date();
      ro.getreferral_postal();
      ro.getreferral_procedure();
      ro.getreferral_callback_time();
    }
     
    ctrl.referral_partner_id = dp.id;
    ctrl.change_practice();
    
    ctrl.next();
    ctrl.prev();
    
    ctrl.name_sort();
    ctrl.name_sort();
    ctrl.name_sort();
    ctrl.phone_sort();
    ctrl.phone_sort();
    ctrl.email_sort();
    ctrl.email_sort();
    ctrl.procedure_sort();
    ctrl.procedure_sort();
    ctrl.date_sort();
    ctrl.date_sort();
    
    ctrl.getpractice_list();
    
        
    //csv stuff
    ctrl.getfile_header();
    ctrl.getfilename();
    ctrl.getnew_line();
    ctrl.getcsv_detail();
    
    System.runAs(my_portal_test_user) {
      ctrl = new portal_referral_out();	      
    }
    
    test.stopTest();
  }
}