src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Center_Location__c</fullName>
        <label>Center Location</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Atlanta</fullName>
                </value>
                <value>
                    <fullName>Atlanta Alpharetta</fullName>
                </value>
                <value>
                    <fullName>Austin</fullName>
                </value>
                <value>
                    <fullName>Baltimore</fullName>
                </value>
                <value>
                    <fullName>Boston Woburn</fullName>
                </value>
                <value>
                    <fullName>Charlotte</fullName>
                </value>
                <value>
                    <fullName>Chicago</fullName>
                </value>
                <value>
                    <fullName>Chicago Deerfield/Northbrook</fullName>
                </value>
                <value>
                    <fullName>Chicago Downers Grove</fullName>
                </value>
                <value>
                    <fullName>Chicago Evanston</fullName>
                </value>
                <value>
                    <fullName>Chicago Naperville</fullName>
                </value>
                <value>
                    <fullName>Chicago Schaumburg</fullName>
                </value>
                <value>
                    <fullName>Cincinnati</fullName>
                </value>
                <value>
                    <fullName>Cleveland</fullName>
                </value>
                <value>
                    <fullName>Cleveland Akron</fullName>
                </value>
                <value>
                    <fullName>Columbia</fullName>
                </value>
                <value>
                    <fullName>Dallas</fullName>
                </value>
                <value>
                    <fullName>Dallas Arlington</fullName>
                </value>
                <value>
                    <fullName>Dallas Fort Worth</fullName>
                </value>
                <value>
                    <fullName>Denver</fullName>
                </value>
                <value>
                    <fullName>Denver Colorado Springs</fullName>
                </value>
                <value>
                    <fullName>Denver Glenwood Springs</fullName>
                </value>
                <value>
                    <fullName>Denver Implant Denistry</fullName>
                </value>
                <value>
                    <fullName>Detroit Southfield</fullName>
                </value>
                <value>
                    <fullName>Houston</fullName>
                </value>
                <value>
                    <fullName>Houston Woodlands</fullName>
                </value>
                <value>
                    <fullName>Kansas City</fullName>
                </value>
                <value>
                    <fullName>Las Vegas</fullName>
                </value>
                <value>
                    <fullName>Los Angeles Orange County</fullName>
                </value>
                <value>
                    <fullName>Los Angeles Torrance</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Center__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Center</label>
        <referenceTo>Center_Information__c</referenceTo>
        <relationshipLabel>Consults</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Center_Information__c.object
<CustomObject>
    <fields>
        <fullName>Center_Webpage__c</fullName>
        <description>Website URL to Center&apos;s Webpage</description>
        <label>Center Webpage</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Local_Front_Desk__c</fullName>
        <label>Local Front Desk</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Map_Directions_URL__c</fullName>
        <label>Map &amp; Directions URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Alabama</fullName>
                </value>
                <value>
                    <fullName>Alaska</fullName>
                </value>
                <value>
                    <fullName>American Samoa</fullName>
                </value>
                <value>
                    <fullName>Arizona</fullName>
                </value>
                <value>
                    <fullName>Arkansas</fullName>
                </value>
                <value>
                    <fullName>California</fullName>
                </value>
                <value>
                    <fullName>Colorado</fullName>
                </value>
                <value>
                    <fullName>Connecticut</fullName>
                </value>
                <value>
                    <fullName>Delaware</fullName>
                </value>
                <value>
                    <fullName>District of Columbia</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Georgia</fullName>
                </value>
                <value>
                    <fullName>Guam</fullName>
                </value>
                <value>
                    <fullName>Hawaii</fullName>
                </value>
                <value>
                    <fullName>Idaho</fullName>
                </value>
                <value>
                    <fullName>Illinois</fullName>
                </value>
                <value>
                    <fullName>Indiana</fullName>
                </value>
                <value>
                    <fullName>Iowa</fullName>
                </value>
                <value>
                    <fullName>Kansas</fullName>
                </value>
                <value>
                    <fullName>Kentucky</fullName>
                </value>
                <value>
                    <fullName>Louisiana</fullName>
                </value>
                <value>
                    <fullName>Maine</fullName>
                </value>
                <value>
                    <fullName>Maryland</fullName>
                </value>
                <value>
                    <fullName>Massachusetts</fullName>
                </value>
                <value>
                    <fullName>Michigan</fullName>
                </value>
                <value>
                    <fullName>Minnesota</fullName>
                </value>
                <value>
                    <fullName>Mississippi</fullName>
                </value>
                <value>
                    <fullName>Missouri</fullName>
                </value>
                <value>
                    <fullName>Montana</fullName>
                </value>
                <value>
                    <fullName>Nebraska</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Street_1__c</fullName>
        <label>Street 1</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Street_2__c</fullName>
        <label>Street 2</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Code__c</fullName>
        <label>Zip Code</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Center Information</label>
    <nameField>
        <label>Center Information Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Center Information</pluralLabel>
    <recordTypes>
        <fullName>Center</fullName>
        <active>true</active>
        <description>Captures Center Information</description>
        <label>Center</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Center_Location__c.object
<CustomObject>
    <description>Master object for maintaining external, Center-specific data such as WinDent scheduling information and revenue collections</description>
    <fields>
        <fullName>Center_Location__c</fullName>
        <description>The name of the Center</description>
        <label>Center Location</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Atlanta</fullName>
                </value>
                <value>
                    <fullName>Austin</fullName>
                </value>
                <value>
                    <fullName>Boston Woburn</fullName>
                </value>
                <value>
                    <fullName>Chicago</fullName>
                </value>
                <value>
                    <fullName>Chicago Deerfield/Northbrook</fullName>
                </value>
                <value>
                    <fullName>Chicago Naperville</fullName>
                </value>
                <value>
                    <fullName>Cleveland</fullName>
                </value>
                <value>
                    <fullName>Cleveland Akron</fullName>
                </value>
                <value>
                    <fullName>Dallas</fullName>
                </value>
                <value>
                    <fullName>Dallas Fort Worth</fullName>
                </value>
                <value>
                    <fullName>Denver</fullName>
                </value>
                <value>
                    <fullName>Denver Colorado Springs</fullName>
                </value>
                <value>
                    <fullName>Denver Glenwood Springs</fullName>
                </value>
                <value>
                    <fullName>Kansas City</fullName>
                </value>
                <value>
                    <fullName>Las Vegas</fullName>
                </value>
                <value>
                    <fullName>Miami</fullName>
                </value>
                <value>
                    <fullName>Miami Aventura</fullName>
                </value>
                <value>
                    <fullName>Miami Fort Lauderdale</fullName>
                </value>
                <value>
                    <fullName>New Jersey Roseland</fullName>
                </value>
                <value>
                    <fullName>Orlando Maitland</fullName>
                </value>
                <value>
                    <fullName>Philadelphia Fort Washington</fullName>
                </value>
                <value>
                    <fullName>Philadelphia Mount Laurel</fullName>
                </value>
                <value>
                    <fullName>Phoenix</fullName>
                </value>
                <value>
                    <fullName>Phoenix Mesa</fullName>
                </value>
                <value>
                    <fullName>Portland</fullName>
                </value>
                <value>
                    <fullName>Sacramento</fullName>
                </value>
                <value>
                    <fullName>Salt Lake City</fullName>
                </value>
                <value>
                    <fullName>San Antonio</fullName>
                </value>
                <value>
                    <fullName>San Francisco Daly City</fullName>
                </value>
                <value>
                    <fullName>San Francisco Oakland</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Center Location</label>
    <nameField>
        <displayFormat>CL-{0}</displayFormat>
        <label>CL ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Center Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PatientPortalMainContentController.cls
/*
06/10/2018  CC  Inital commit
*/

public class PatientPortalMainContentController {
    @AuraEnabled
    public static Account getAccountInfo(Id accountId) {
    	Account account = [SELECT Id, Name,Center_Location__c,Center__r.Name,Center__r.Id,Phone
                           	FROM Account
                           	WHERE Id = :accountId
                           	LIMIT 1];
        return account;
    }
    
    @AuraEnabled 
    public static Center_Information__c getCenterInfo(Id centerId) {
        Center_Information__c center = [SELECT Street_1__c, Street_2__c, City__c, State__c, Zip_Code__c, Center_Webpage__c, Map_Directions_URL__c, Local_Front_Desk__c, Name
                        	FROM Center_Information__c
                        	WHERE Id = :centerId
                        	LIMIT 1];
        return center;
    }
    
   	@AuraEnabled
    public static String getBaseUrl(String search){
        return String.valueOf(System.URL.getSalesforceBaseUrl().toExternalForm());
    }
}