src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Center__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Center</label>
        <referenceTo>Center_Information__c</referenceTo>
        <relationshipLabel>Consults</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Center_Information__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DoseSpot_Clinic_ID__c</fullName>
        <label>DoseSpot Clinic ID</label>
        <length>15</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DoseSpot_Clinic_Key__c</fullName>
        <description>Value required for communicating with DoseSpot API</description>
        <label>DoseSpot Clinic Key</label>
        <length>63</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Sales Region (Lookup)</label>
        <referenceTo>Sales_Region__c</referenceTo>
        <relationshipLabel>Center Information</relationshipLabel>
        <relationshipName>Center_Information</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Sales_Region__c</fullName>
        <label>Sales Region</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Northeast</fullName>
                </value>
                <value>
                    <fullName>Southeast</fullName>
                </value>
                <value>
                    <fullName>Texas North</fullName>
                </value>
                <value>
                    <fullName>Texas South</fullName>
                </value>
                <value>
                    <fullName>Southwest</fullName>
                </value>
                <value>
                    <fullName>Midwest</fullName>
                </value>
                <value>
                    <fullName>Northwest</fullName>
                </value>
                <value>
                    <fullName>New Centers</fullName>
                </value>
                <value>
                    <fullName>Mid-Atlantic</fullName>
                </value>
                <value>
                    <fullName>Florida</fullName>
                </value>
                <value>
                    <fullName>Great Lakes</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Center Information</label>
    <nameField>
        <label>Center Information Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Center Information</pluralLabel>
    <recordTypes>
        <fullName>Center</fullName>
        <active>true</active>
        <description>Captures Center Information</description>
        <label>Center</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Call_Center_Agent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Call Center Agent (Lookup)</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Center__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Center</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1) OR (2 AND 3) OR 4</booleanFilter>
            <errorMessage>The center you are trying to use is no longer avaliable.</errorMessage>
            <filterItems>
                <field>Center_Information__c.Allow_Center_Selection__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.CreatedDate</field>
                <operation>lessThan</operation>
                <value>3/1/2013 12:00 AM</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>Call Center Agent Infocision, Call Center - Supervisor Infocision, System Administrator</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>System Administrator</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Center_Information__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Sales_Region__c.object
<CustomObject>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RBD__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The RBD for this sales region</description>
        <label>RBD</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Sales_Regions1</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Sales Region</label>
    <nameField>
        <label>Sales Region Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sales Regions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestDataFactory.cls
/*
05/14/2018  CC  Inital commit
*/

@isTest
public with sharing class TestDataFactory {
	public TestDataFactory() {
	}

	public static Sales_Region__c  CreateTestRegion() {
    	Sales_Region__c region = new Sales_Region__c(Name = 'Test Region',
                                                 Active__c = true,
                                                 RBD__c = UserInfo.getUserId()
                                               );
		return region;									   
	}

	public static Center_Information__c CreateTestCenter() {
		Sales_Region__c region = CreateTestRegion();
		insert region;
    	Center_Information__c center = new Center_Information__c(Name = 'Test Center',
                                                             	Region__c = region.Id,
																Latlong__Longitude__s = 30,
																Latlong__Latitude__s = 30,
																DoseSpot_Clinic_ID__c = '596',
																DoseSpot_Clinic_Key__c = 'Dt5K6ktpZWYMFkK6tWJVhGdyR7KsjdYP'
															);
     	return center;
  	}

	public static Account CreateTestAccount() {
		Center_Information__c center = CreateTestCenter();
		insert center;
		Account account = new Account(FirstName = 'Firstname',
									LastName = 'Lastname',
									BillingStreet = '123 Main St',
									BillingCity = 'Denver',
									BillingState = 'Colorado',
									Center__c = center.Id
									);
     return account;
  }
  	
	public static List<Lead> CreateTestLeads() {
		Map<String, String> names = new Map<String, String>{
										'Michael' => 'Smith',
										'Miles' => 'Jones',
										'Kevin' => 'Michaelson',
										'Michelle' => 'Gonzalez',
										'Lewis' => 'Chen',
										'Zach' => 'Roberts',
										'Tyranosaurus' => 'Rex',
										'Zi' => 'Chang',
										'Sarah' => 'Adams',
										'Charles' => 'Seib ert',
										'Amanda' => 'Fox'
									};

		List<lead> leads = new List<lead>();
		for(String key : names.keySet()) {
			Lead lead = new Lead(FirstName = key,
								LastName = names.get(key),
								Street = '123 Main St',
								City = 'Denver',
								State = 'Colorado'
							);
			leads.add(lead);
		}
		return leads;
	}	

	public static Lead CreateTestLead() {
		Lead lead = new Lead();
		lead.lastName = 'Smith';
		lead.firstName = 'James';	
		lead.Call_Center_Agent__c = UserInfo.getUserId();	
		return lead;
	}	

	//SMS Related 
	public static void CreateSendIds() {
		//Create senderids
        List<smagicinteract__SMS_SenderId__c> senderIds = new List<smagicinteract__SMS_SenderId__c>();
        senderIds.add(new smagicinteract__SMS_SenderId__c(smagicinteract__senderId__c = '1'));
        senderIds.add(new smagicinteract__SMS_SenderId__c(smagicinteract__senderId__c = '2'));
        insert senderIds;
        smagicinteract__SMS_SenderId__c senderId = [SELECT Id, smagicinteract__senderId__c 
                                                        FROM smagicinteract__SMS_SenderId__c
                                                        WHERE smagicinteract__senderId__c = '1'
                                                        LIMIT 1];
		//Create   default senderid
        smagicinteract__SenderId_Profile_Map__c senderIdProfileMap = new smagicinteract__SenderId_Profile_Map__c();
        senderIdProfileMap.smagicinteract__SenderId_Lookup__c = senderId.Id;
        senderIdProfileMap.smagicinteract__Profile_Id__c = userinfo.getProfileId();
        insert senderIdProfileMap;
	}
									
}