src/objects/Awaiting_Bulk_Print__c.object
<CustomObject>
    <description>Table that holds a list of print jobs waiting to be printed from the bulk queue.  These records get deleted once a bulk print job is marked as successful.</description>
    <fields>
        <fullName>Batch_Form__c</fullName>
        <description>The type of form waiting to be bulk printed. test</description>
        <label>Batch Form</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BCP Letter</fullName>
                </value>
                <value>
                    <fullName>Welcome Letter</fullName>
                </value>
                <value>
                    <fullName>Seminar Letter</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lead_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The lead record the print jobs is related to</description>
        <label>Lead Id</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Awaiting Bulk Prints</relationshipLabel>
        <relationshipName>Awaiting_Bulk_Print_Lead</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Printed</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Submitted_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>User who submitted the bulk print request</description>
        <label>Submitted By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Awaiting_Bulk_Subu</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Submitted_Time__c</fullName>
        <defaultValue>NOW()</defaultValue>
        <description>Time the print job was submitted</description>
        <label>Submitted Time</label>
        <type>DateTime</type>
    </fields>
    <label>Awaiting Bulk Print</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Awaiting Bulk Print Num</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Awaiting Bulk Prints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>BCP_DVD_Packet_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>BCP/DVD Packet Sent</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LeadBulkPrintPendingService.cls
public without sharing class LeadBulkPrintPendingService {
    public static Set<Id> AwaitingBulkPrintExists(Set<Id> leadIds, String batchForm, String status) {
		List<Awaiting_Bulk_Print__c> bulkPrints = [	SELECT 	Lead_Id__c 
														FROM Awaiting_Bulk_Print__c 
														WHERE Batch_Form__c = :batchForm
															AND Lead_Id__c in :leadIds
															AND Status__c = :status];
		leadIds = new Set<Id>();
		for(Awaiting_Bulk_Print__c bulkPrint : bulkPrints ) {
			leadIds.add(bulkPrint.Lead_Id__c);
		}
		return leadIds;
	}
   
  	public static void InsertBulkPrintRecords(Set<Id> leads, String batchForm, String status) {
		List<Awaiting_Bulk_Print__c> bulkPrints = new List<Awaiting_Bulk_Print__c>();
		List<Task> tasks = new List<Task>();
		Set<Id> bulkPrintsExist = AwaitingBulkPrintExists(leads, batchForm, status);
		for(Id lead : leads) {
			if(!bulkPrintsExist.contains(lead)){
				bulkPrints.add(new Awaiting_Bulk_Print__c (Batch_Form__c = batchForm, Lead_Id__c = lead, Submitted_Time__c = Datetime.now(), Submitted_By__c = Userinfo.getUserId(), Status__c = status));
				tasks.add(new Task(WhoId = lead, OwnerId = Userinfo.getUserId(), Subject = batchForm, Type = 'Other', Activity_Type__c = 'Mail', Outcome__c = 'Queued', Call_No_Answer__c = false, Status = 'Completed'));
			}
		} 
		System.debug('Inserting: ' + tasks.size() + ' tasks');
		insert tasks;
		System.debug('Inserting: ' + bulkPrints.size() + ' bulkPrints');
		insert bulkPrints;
		//Update BCP_DVD_Packet_Sent__c for leads
		List<Lead> updateLeads = [SELECT BCP_DVD_Packet_Sent__c , Id
							FROM Lead
							WHERE Id in :leads];
							
		for(Lead lead : updateLeads ) {
			lead.BCP_DVD_Packet_Sent__c = true;
		}					
		update updateLeads;
	}
}