src/objects/Awaiting_Bulk_Print__c.object
<CustomObject>
    <description>Table that holds a list of print jobs waiting to be printed from the bulk queue.  These records get deleted once a bulk print job is marked as successful.</description>
    <fields>
        <fullName>Batch_Form__c</fullName>
        <description>The type of form waiting to be bulk printed. test</description>
        <label>Batch Form</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BCP Letter</fullName>
                </value>
                <value>
                    <fullName>Welcome Letter</fullName>
                </value>
                <value>
                    <fullName>Seminar Letter</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lead_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The lead record the print jobs is related to</description>
        <label>Lead Id</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Awaiting Bulk Prints</relationshipLabel>
        <relationshipName>Awaiting_Bulk_Print_Lead</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Printed</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Submitted_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>User who submitted the bulk print request</description>
        <label>Submitted By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Awaiting_Bulk_Subu</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Awaiting Bulk Print</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Awaiting Bulk Print Num</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Awaiting Bulk Prints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>BCP_DVD_Packet_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>BCP/DVD Packet Sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Pre_Screen_Time__c</fullName>
        <label>Pre Screen Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Pre_Screen__c</fullName>
        <label>Pre Screen</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Checked</fullName>
                </value>
                <value>
                    <fullName>Green</fullName>
                </value>
                <value>
                    <fullName>Yellow</fullName>
                </value>
                <value>
                    <fullName>Red</fullName>
                </value>
                <value>
                    <fullName>Blue (No Hit)</fullName>
                </value>
                <value>
                    <fullName>Website Down-No Prescreen</fullName>
                </value>
                <value>
                    <fullName>PO Box</fullName>
                </value>
                <value>
                    <fullName>Insufficient Information</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Warranty_ID__c</fullName>
        <description>A unique ID that we will use to track warranty info on anything tied to this patient (implants,  bridges,  dentures,  etc)</description>
        <externalId>true</externalId>
        <label>Warranty ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ScheduleBCPPrintQueueTests.cls
/*
05/14/2018  CC  Inital commit
05/31/2018	CC	Changed test from waiting time of 5 days to 24 hours
*/

@isTest
private class ScheduleBCPPrintQueueTests {
	static Lead lead;
	static Awaiting_Bulk_Print__c bulkPrint;
	
	private static Lead createLead(Integer hoursPassed, Integer counter) {
		//Create lead for testing 
		lead = TestDataFactory.CreateTestLead();
		lead.BCP_DVD_Packet_Sent__c = false;
		lead.Street = '1234 Main St';
		lead.City = 'Denver';
		lead.State = 'CO';
		lead.PostalCode = '80111';
		lead.Warranty_ID__c = 'BA8D6569-9208-4' + counter;
		lead.Pre_Screen__c = 'Green';
        lead.Pre_Screen_Time__c = datetime.now().addDays(hoursPassed).addHours(-6);
		return lead;
	}

  	private static Integer ReturnAwaitingBulkPrintCount() {
  		return database.countQuery('select count() from Awaiting_Bulk_Print__c');
  	}

  	testMethod static void TestScheduleJobCreatedRecordsLeadsUpdatedFiveDaysBefore(){
		  System.debug('TestScheduleJobCreatedRecordsLeadsUpdatedFiveDaysBefore');
		Test.startTest();
		Integer counter = 0;
		Util_TriggerContext.alteralreadyprocessed(true);
		List<Lead> leads = new List<Lead>();
		while(counter < 100) {
			leads.add(createLead(-2, counter));
			counter = counter + 1;
		}
		insert leads;
		System.debug(leads);
		ScheduleBCPPrintQueue printQueue = new ScheduleBCPPrintQueue();
		printQueue.execute(null);
		//Our mock lead should trigger an awakiting_bulk_print to be inserted
		System.debug('Print queue: ' + ReturnAwaitingBulkPrintCount());
		System.assert(ReturnAwaitingBulkPrintCount() == 100);
		Test.stopTest();    
	}

  	testMethod static void TestScheduleJobSetBCPSentTrueLeadUpdatedFiveDaysBefore(){
		Test.startTest();
		insert createLead(-2, 1);
		ScheduleBCPPrintQueue printQueue = new ScheduleBCPPrintQueue();
		printQueue.execute(null);
		//Our mock lead should trigger an awakiting_bulk_print to be inserted
		System.debug('Print queue: ' + ReturnAwaitingBulkPrintCount());
		lead = [SELECT BCP_DVD_Packet_Sent__c
				FROM Lead
				Where Id = :lead.id];
        System.debug(lead);
		System.assert(lead.BCP_DVD_Packet_Sent__c == true);
		Test.stopTest();    
	}	

  	testMethod static void TestScheduleJobDoesNotCreatedDupRecord(){
		Test.startTest();
		insert createLead(-2, 1);	
		Awaiting_Bulk_Print__c bulkQueue = new Awaiting_Bulk_Print__c();
		bulkQueue.Batch_Form__c = 'BCP Letter';
		bulkQueue.Lead_Id__c = lead.Id;
		bulkQueue.Submitted_By__c = Userinfo.getUserId();
		bulkQueue.Status__c = 'Pending';
		insert bulkQueue;
		ScheduleBCPPrintQueue printQueue = new ScheduleBCPPrintQueue();
		printQueue.execute(null);
		System.assert(ReturnAwaitingBulkPrintCount() == 1);
		Test.stopTest();    
	}

  	testMethod static void TestScheduleJobDoNotCreatedRecordLeadUpdatedTwoDaysBefore(){
		Test.startTest();
		insert createLead(-48, 1);
		ScheduleBCPPrintQueue printQueue = new ScheduleBCPPrintQueue();
		printQueue.execute(null);
		//Our mock lead should trigger an awakiting_bulk_print to be inserted
		System.assert(ReturnAwaitingBulkPrintCount() == 0);
		Test.stopTest();    
	}
}