src/objects/Awaiting_Bulk_Print__c.object
<CustomObject>
    <description>Table that holds a list of print jobs waiting to be printed from the bulk queue.  These records get deleted once a bulk print job is marked as successful.</description>
    <fields>
        <fullName>Batch_Form__c</fullName>
        <description>The type of form waiting to be bulk printed. test</description>
        <label>Batch Form</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>BCP Letter</fullName>
                </value>
                <value>
                    <fullName>Welcome Letter</fullName>
                </value>
                <value>
                    <fullName>Seminar Letter</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Lead_Id__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The lead record the print jobs is related to</description>
        <label>Lead Id</label>
        <referenceTo>Lead</referenceTo>
        <relationshipLabel>Awaiting Bulk Prints</relationshipLabel>
        <relationshipName>Awaiting_Bulk_Print_Lead</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Pending</fullName>
                </value>
                <value>
                    <fullName>Printed</fullName>
                </value>
                <value>
                    <fullName>Complete</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Awaiting Bulk Print</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Awaiting Bulk Print Num</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Awaiting Bulk Prints</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>BCP_DVD_Packet_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>BCP/DVD Packet Sent</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>DateTime_Consult_Scheduled__c</fullName>
        <label>Date/Time Consult Scheduled</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Pre_Screen_Time__c</fullName>
        <label>Pre Screen Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Pre_Screen__c</fullName>
        <label>Pre Screen</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Checked</fullName>
                </value>
                <value>
                    <fullName>Green</fullName>
                </value>
                <value>
                    <fullName>Yellow</fullName>
                </value>
                <value>
                    <fullName>Red</fullName>
                </value>
                <value>
                    <fullName>Blue (No Hit)</fullName>
                </value>
                <value>
                    <fullName>Website Down-No Prescreen</fullName>
                </value>
                <value>
                    <fullName>PO Box</fullName>
                </value>
                <value>
                    <fullName>Insufficient Information</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Welcome_Packet_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Welcome packet was sent to patient</description>
        <label>Mailed Welcome Packet</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/ScheduleBCPPrintQueue.cls
/*
05/14/2018  CC  Inital commit
05/31/2018  CC  Changed the wait time from 5 days to 24 hour after the lead record has been modified
*/

global class ScheduleBCPPrintQueue implements Schedulable {
    static final String poBoxStatus = 'PO Box';
    static final String notCheckedStatus = 'Not Checked';
    static final String insufficientInformationStatus = 'Insufficient Information';
    static final Integer startDateRange = -2;
    static final Integer endDateRange = -1;
    static String bcpBatchForm = 'BCP Letter';
    static String pendingStatus = 'Pending';
    global void execute(SchedulableContext sc) {
        System.debug('ScheduleBCPPrintQueue Started');
        System.debug('Looking for leads that have been pre_screen between ' + Date.today().addDays(startDateRange) + ' and ' + Date.today().addDays(endDateRange));
        List<lead> leads = new List<lead>();
        Util_TriggerContext.alteralreadyprocessed(true);
        leads = [SELECT Id, BCP_DVD_Packet_Sent__c 
                    FROM lead
                    WHERE
                        Pre_Screen__c != :poBoxStatus
                        AND Pre_Screen__c != :notCheckedStatus
                        AND Pre_Screen__c != :insufficientInformationStatus
                        AND Pre_Screen__c != null
                        AND DateTime_Consult_Scheduled__c = null
                        AND ((LastModifiedDate >= :Date.today().addDays(startDateRange)
                        AND LastModifiedDate < :Date.today().addDays(endDateRange)) OR (
                        Pre_Screen_Time__c >= :Date.today().addDays(startDateRange)
                        AND Pre_Screen_Time__c < :Date.today().addDays(endDateRange)))
                        AND BCP_DVD_Packet_Sent__c = false
                        AND Welcome_Packet_Sent__c = false
                        AND Id Not In (SELECT Lead_Id__c 
										FROM Awaiting_Bulk_Print__c 
										WHERE Batch_Form__c = :bcpBatchForm
											AND Status__c = :pendingStatus)];
        Set<Id> leadIds = (new Map<Id,SObject>(leads)).keySet();
        System.debug(leadIds.size() + ' leads record found');
        LeadBulkPrintPendingService.InsertBulkPrintRecords(leadIds, bcpBatchForm, pendingStatus);
        System.debug('ScheduleBCPPrintQueue Finished');
    }
}