src/objects/Center_Information__c.object
<CustomObject>
    <label>Center Information</label>
    <nameField>
        <label>Center Information Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Center Information</pluralLabel>
    <recordTypes>
        <fullName>Center</fullName>
        <active>true</active>
        <description>Captures Center Information</description>
        <label>Center</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Center_Location__c.object
<CustomObject>
    <description>Master object for maintaining external, Center-specific data such as WinDent scheduling information and revenue collections</description>
    <fields>
        <fullName>Center_Location__c</fullName>
        <description>The name of the Center</description>
        <label>Center Location</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Atlanta</fullName>
                </value>
                <value>
                    <fullName>Austin</fullName>
                </value>
                <value>
                    <fullName>Boston Woburn</fullName>
                </value>
                <value>
                    <fullName>Chicago</fullName>
                </value>
                <value>
                    <fullName>Chicago Deerfield/Northbrook</fullName>
                </value>
                <value>
                    <fullName>Chicago Naperville</fullName>
                </value>
                <value>
                    <fullName>Cleveland</fullName>
                </value>
                <value>
                    <fullName>Cleveland Akron</fullName>
                </value>
                <value>
                    <fullName>Dallas</fullName>
                </value>
                <value>
                    <fullName>Dallas Fort Worth</fullName>
                </value>
                <value>
                    <fullName>Denver</fullName>
                </value>
                <value>
                    <fullName>Denver Colorado Springs</fullName>
                </value>
                <value>
                    <fullName>Denver Glenwood Springs</fullName>
                </value>
                <value>
                    <fullName>Kansas City</fullName>
                </value>
                <value>
                    <fullName>Las Vegas</fullName>
                </value>
                <value>
                    <fullName>Miami</fullName>
                </value>
                <value>
                    <fullName>Miami Aventura</fullName>
                </value>
                <value>
                    <fullName>Miami Fort Lauderdale</fullName>
                </value>
                <value>
                    <fullName>New Jersey Roseland</fullName>
                </value>
                <value>
                    <fullName>Orlando Maitland</fullName>
                </value>
                <value>
                    <fullName>Philadelphia Fort Washington</fullName>
                </value>
                <value>
                    <fullName>Philadelphia Mount Laurel</fullName>
                </value>
                <value>
                    <fullName>Phoenix</fullName>
                </value>
                <value>
                    <fullName>Phoenix Mesa</fullName>
                </value>
                <value>
                    <fullName>Portland</fullName>
                </value>
                <value>
                    <fullName>Sacramento</fullName>
                </value>
                <value>
                    <fullName>Salt Lake City</fullName>
                </value>
                <value>
                    <fullName>San Antonio</fullName>
                </value>
                <value>
                    <fullName>San Francisco Daly City</fullName>
                </value>
                <value>
                    <fullName>San Francisco Oakland</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Center Location</label>
    <nameField>
        <displayFormat>CL-{0}</displayFormat>
        <label>CL ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Center Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Call_Center_Agent_Owner__c</fullName>
        <description>Call Center Agent who owns the prospective patient.</description>
        <label>Call Center Agent</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Andrea Palmer</fullName>
                </value>
                <value>
                    <fullName>Andrew Deutsch</fullName>
                </value>
                <value>
                    <fullName>Andy McMullen</fullName>
                </value>
                <value>
                    <fullName>Angela Wuelling</fullName>
                </value>
                <value>
                    <fullName>Audrey Dinges</fullName>
                </value>
                <value>
                    <fullName>Barb Emerick</fullName>
                </value>
                <value>
                    <fullName>Cameron Fisher</fullName>
                </value>
                <value>
                    <fullName>Carrie Strohmeyer</fullName>
                </value>
                <value>
                    <fullName>David Cardenas</fullName>
                </value>
                <value>
                    <fullName>Deb Scheer</fullName>
                </value>
                <value>
                    <fullName>Desi Garcia</fullName>
                </value>
                <value>
                    <fullName>Devonne Espinoza</fullName>
                </value>
                <value>
                    <fullName>Emily Fickinger</fullName>
                </value>
                <value>
                    <fullName>Eowyn Suchan</fullName>
                </value>
                <value>
                    <fullName>Heather Storer</fullName>
                </value>
                <value>
                    <fullName>Javier Mantilla</fullName>
                </value>
                <value>
                    <fullName>John Tolmich</fullName>
                </value>
                <value>
                    <fullName>Kesley Low</fullName>
                </value>
                <value>
                    <fullName>Kim Goehring</fullName>
                </value>
                <value>
                    <fullName>Kris Karge</fullName>
                </value>
                <value>
                    <fullName>Krista Schaad</fullName>
                </value>
                <value>
                    <fullName>Kristine Feuerborn</fullName>
                </value>
                <value>
                    <fullName>Lisa Avrett</fullName>
                </value>
                <value>
                    <fullName>Marcella Velasquez</fullName>
                </value>
                <value>
                    <fullName>Maria Jimenez</fullName>
                </value>
                <value>
                    <fullName>Marianne Mills</fullName>
                </value>
                <value>
                    <fullName>Mariann Maestas</fullName>
                </value>
                <value>
                    <fullName>Mary Helen Turner</fullName>
                </value>
                <value>
                    <fullName>Meridith Hertach</fullName>
                </value>
                <value>
                    <fullName>Michelle Hernandez</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Call_Center_Agent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Call Center Agent (Lookup)</label>
        <referenceTo>User</referenceTo>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Center_Location__c</fullName>
        <description>Specific Market or Division of ClearChoice Dental Implant Centers.</description>
        <label>Center Location</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Atlanta</fullName>
                </value>
                <value>
                    <fullName>Atlanta Alpharetta</fullName>
                </value>
                <value>
                    <fullName>Austin</fullName>
                </value>
                <value>
                    <fullName>Boston Woburn</fullName>
                </value>
                <value>
                    <fullName>Charlotte</fullName>
                </value>
                <value>
                    <fullName>Chicago</fullName>
                </value>
                <value>
                    <fullName>Chicago Downers Grove</fullName>
                </value>
                <value>
                    <fullName>Chicago Naperville</fullName>
                </value>
                <value>
                    <fullName>Chicago Schaumburg</fullName>
                </value>
                <value>
                    <fullName>Cincinnati</fullName>
                </value>
                <value>
                    <fullName>Cleveland</fullName>
                </value>
                <value>
                    <fullName>Columbia</fullName>
                </value>
                <value>
                    <fullName>Dallas</fullName>
                </value>
                <value>
                    <fullName>Dallas Arlington</fullName>
                </value>
                <value>
                    <fullName>Denver</fullName>
                </value>
                <value>
                    <fullName>Detroit Southfield</fullName>
                </value>
                <value>
                    <fullName>Houston</fullName>
                </value>
                <value>
                    <fullName>Houston Woodlands</fullName>
                </value>
                <value>
                    <fullName>Kansas City</fullName>
                </value>
                <value>
                    <fullName>Las Vegas</fullName>
                </value>
                <value>
                    <fullName>Los Angeles Orange County</fullName>
                </value>
                <value>
                    <fullName>Los Angeles Torrance</fullName>
                </value>
                <value>
                    <fullName>Los Angeles West Covina</fullName>
                </value>
                <value>
                    <fullName>Miami Fort Lauderdale</fullName>
                </value>
                <value>
                    <fullName>Minneapolis</fullName>
                </value>
                <value>
                    <fullName>Minneapolis Roseville</fullName>
                </value>
                <value>
                    <fullName>New Jersey Roseland</fullName>
                </value>
                <value>
                    <fullName>New Market Not Yet Open</fullName>
                </value>
                <value>
                    <fullName>Orlando Maitland</fullName>
                </value>
                <value>
                    <fullName>Philadelphia Fort Washington</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Center__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Center</label>
        <lookupFilter>
            <active>true</active>
            <booleanFilter>(1) OR (2 AND 3) OR 4</booleanFilter>
            <errorMessage>The center you are trying to use is no longer avaliable.</errorMessage>
            <filterItems>
                <field>Center_Information__c.Allow_Center_Selection__c</field>
                <operation>equals</operation>
                <value>True</value>
            </filterItems>
            <filterItems>
                <field>$Source.CreatedDate</field>
                <operation>lessThan</operation>
                <value>3/1/2013 12:00 AM</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>Call Center Agent Infocision, Call Center - Supervisor Infocision, System Administrator</value>
            </filterItems>
            <filterItems>
                <field>$Profile.Name</field>
                <operation>equals</operation>
                <value>System Administrator</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Center_Information__c</referenceTo>
        <relationshipLabel>Leads</relationshipLabel>
        <relationshipName>Leads</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/Test_SyncCallCtrFields.cls
/**********************************************************************************
Name    : Test_SyncCallCtrFields
Usage   : For the Lead object, this Trigger Updates the Call_Center_Agent_Owner__c based on the Call_Center_Agent__r.Name
                                                    and Center_Location__c from Lead.Center__r.Name.

CHANGE HISTORY
===============================================================================
DATE            NAME                  DESC
2011-03-07     Mike Merino            Initial release      
2011-09-09		Seth Davidow		  Update to remove Id dependencies           

*************************************************************************************/
@isTest
private class Test_SyncCallCtrFields {
    testMethod static void testIt() {
return;  //sjd tmp
        Lead l1 = new Lead();
        id usgId = userinfo.getUserId();
		Center_Information__c center = [select id from Center_Information__c limit 1];

        // user setup due to 
        //    lead validation rule: Validate_that_Call_Center_Agent_Current
        //    lead custom field Call Center Agent (Lookup);validation rule: Validate_that_Call_Center_Agent_Current
for (user u:[select u.firstname, u.lastname, u.id from User u where u.id = :usgId limit 1])
{
        String Lname = u.LastName;
        String Fname =u.firstname; 
  //      system.debug('### '+usgId+'--'+lname);
        l1.lastName =lname;
        l1.firstName =fname;
    //    system.debug('### '+l1);
        l1.company=null; 
        l1.status ='Not Scheduled'; 
        l1.Call_Center_Agent__c = u.Id; //call_ctr_agent must = usgId
        l1.center__c = center.id; //'a0S40000002P7MnEAK'; //  atlanta
        
        insert l1;
        system.debug('### Test_SyncCallCtrFields '+l1);
    
 // now test WelcomePkgSent trigger    , whoId must be Lead.id
// set email flag in lead
List<task> t = new List<task>{ new task(
        WhoId = l1.Id,
       // WhatID = l1.id,
        Subject='this is Email: myTest',
        Status='New',
        Priority='Normal')};

        insert t; 
        system.debug('### Test_SyncCallCtrFields Task t='+t); 
        
        List<task> taskstoupdate = New List<task>{ [select id from task where id in :t]};
             for(task tOK:taskstoupdate)
             {
                 tOK.status = 'Completed';

                 Update taskstoupdate;
             }
// set welcome flag in lead             
        List<task> t1 = new List<task>{ new task(
        WhoId = l1.Id,
       // WhatID = l1.id,
        Subject='You are Welcome',
        Status='New',
        Priority='Normal')};

        insert t1; 
        system.debug('### Task Test_SyncCallCtrFields t1='+t1); 

        List<task> taskstoupdate1 = New List<task>{ [select id from task where id in :t1]};
             for(task tOK:taskstoupdate)
             {
                 tOK.status = 'Active';

                 Update taskstoupdate1;
             }
       //  flags already set in lead
        List<task> taskstoupdate2 = New List<task>{ [select id from task where id in :t1]};
             for(task tOK:taskstoupdate)
             {
                 tOK.Priority = 'Completed';

                 Update taskstoupdate2;
             }             
       }   
    }
 }