src/objects/Center_Information__c.object
<CustomObject>
    <label>Center Information</label>
    <nameField>
        <label>Center Information Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Center Information</pluralLabel>
    <recordTypes>
        <fullName>Center</fullName>
        <active>true</active>
        <description>Captures Center Information</description>
        <label>Center</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Dental_Practice__c.object
<CustomObject>
    <description>A table to store one record for each unique dental practice we will be looking at for the referral program</description>
    <fields>
        <fullName>Center_Information__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Indicates the center this practice will be used with for referral purposes</description>
        <label>Center Information</label>
        <referenceTo>Center_Information__c</referenceTo>
        <relationshipLabel>Dental Practices</relationshipLabel>
        <relationshipName>Dental_Practices</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Dental Practice</label>
    <nameField>
        <label>Dental Practice Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Dental Practices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>Dental_Practice__c</fullName>
        <formula>Contact.Account.Dental_Practice_Partner__c</formula>
        <label>Dental Practice</label>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/newPracticeFeed.cls
global without sharing class newPracticeFeed {
	
  @future 
  public static void newCenterFeedPostLink(String center_id, String feed_body, String link_url, String link_name) {
  	try {
  	  Center_Information__c ci = [select id,name from Center_Information__c where id = :center_id];
  	  String group_name = ci.name + ' Practice Development';
  	  CollaborationGroup cg = [select id from CollaborationGroup where name = :group_name];
  	  FeedItem testFeed1 = new FeedItem(Body=feed_body, ParentId = cg.Id, Type='AdvancedTextPost', linkurl = 'https://na2.salesforce.com' + link_url, title = link_name);
	  insert testFeed1;
  	} catch (Exception e) {
  	  
  	}
  }
  
  @future
  public static void newCenterFeedPost(String center_id, String feed_body) {
  	try {
  	  Center_Information__c ci = [select id,name from Center_Information__c where id = :center_id];
  	  String group_name = ci.name + ' Practice Development';
  	  CollaborationGroup cg = [select id from CollaborationGroup where name = :group_name];
  	  FeedItem testFeed1 = new FeedItem(Body=feed_body, ParentId = cg.Id, Type='TextPost');
	  insert testFeed1;
  	} catch (Exception e) {
  	  
  	}
  }
  
  @future 
  public static void newPracticeFeedPostLink(String dp_id, String feed_body, String link_url, String link_name) {
  	try {
      Network n = [select id from network where name = 'Practice Development' limit 1];
  	  Dental_Practice__c ci = [select id,name from Dental_Practice__c where id = :dp_id];
  	  String group_name = ci.name + ' Referral Feed';
  	  CollaborationGroup cg = [select id from CollaborationGroup where name = :group_name];
  	  FeedItem testFeed1 = new FeedItem(Body=feed_body, ParentId = cg.Id, Type='AdvancedTextPost', linkurl = 'https://clearchoice.force.com' + link_url, title = link_name, networkscope = n.id);
  	  System.debug('Feed Item : ' + testFeed1);
	  insert testFeed1;
  	} catch (Exception e) {
  		
  	}
  }
  
  @future 
  public static void newPracticeFeedPost(String dp_id, String feed_body) {
  	try {
  	  Network n = [select id from network where name = 'Practice Development' limit 1];
  	  Dental_Practice__c ci = [select id,name from Dental_Practice__c where id = :dp_id];
  	  String group_name = ci.name + ' Referral Feed';
  	  CollaborationGroup cg = [select id from CollaborationGroup where name = :group_name];
  	  FeedItem testFeed1 = new FeedItem(Body=feed_body, ParentId = cg.Id, Type='TextPost', networkscope = n.id);
	  insert testFeed1;
  	} catch (Exception e) {
  		
  	}
  }
  
  @future 
  public static void create_new_practice_feed(ID uid, String pname, String cname) {
  	try {
  	  Network n = [select id from network where name = 'Practice Development' limit 1];
  	  //check to see if we already have a group for this practice
  	  String group_name = pname + ' Referral Feed';
  	  Integer cnt = [select count() from CollaborationGroup where Name = :group_name];
  	  CollaborationGroup cg;
  	  if(cnt>0) {
  	  	cg = [select id from CollaborationGroup where Name = :group_name];
  	  }
  	  else {
  	    cg = new CollaborationGroup(collaborationtype = 'Private', Description = 'A group to monitor referral events for referral practice ' + pname,
          networkid = n.id, canhaveguests = false, name = pname + ' Referral Feed');
        insert cg;
  	  }
      CollaborationGroupMember cgm = new CollaborationGroupMember(CollaborationGroupID = cg.id, CollaborationRole = 'Admin', Memberid = uid, NotificationFrequency = 'D');
      insert cgm;
  	} catch (Exception e) {
  		System.debug('Exception ' + e);
  	}
  	
  	//try to add a feeditem to the center group  
  	try {
  	  String group_name = cname + ' Practice Development'; 
  	  CollaborationGroup cg = [select id from CollaborationGroup where name = :group_name];
	  FeedItem testFeed1 = new FeedItem(Body='New Practice has just been added to the portal - ' + pname, ParentId = cg.Id, Type='AdvancedTextPost', linkurl = 'https://na2.salesforce.com/' + uid, title = 'View User');
	  insert testFeed1;
  	} catch (Exception e) {
  		System.debug('Exception ' + e);
  	}
  	
  }
}