src/objects/Center_Information__c.object
<CustomObject>
    <fields>
        <fullName>Use_Alternate_Calendar_URL__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Use Alternate Calendar URL</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Use_Alternate_Url__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Use Alternate Url</label>
        <type>Checkbox</type>
    </fields>
    <label>Center Information</label>
    <nameField>
        <label>Center Information Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Center Information</pluralLabel>
    <recordTypes>
        <fullName>Center</fullName>
        <active>true</active>
        <description>Captures Center Information</description>
        <label>Center</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Navigation_Header__c.object
<CustomObject>
    <description>Contains a row for each section header on the dental practice navigation menu</description>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <description>Controls the order in which the sections display on the navigation menu</description>
        <label>Sort Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Sub_System__c</fullName>
        <label>Sub System</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Setup</fullName>
                </value>
                <value>
                    <fullName>Gear</fullName>
                </value>
                <value>
                    <fullName>Clinical Navigation</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Navigation Header</label>
    <nameField>
        <label>Navigation Headers Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Navigation Headers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Navigation_Page__c.object
<CustomObject>
    <description>One row for each navigation item on the drop down navigation menu</description>
    <fields>
        <fullName>Alt_Page_URL__c</fullName>
        <label>Alt Page URL</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Hyperlink_Target__c</fullName>
        <label>Hyperlink Target</label>
        <length>25</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Image_Name_Hover__c</fullName>
        <label>Image Name Hover</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Image_Name__c</fullName>
        <label>Image Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nav_Color__c</fullName>
        <description>Controls the color of the menu item</description>
        <label>Nav Color</label>
        <length>8</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Navigation_Header__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Navigation Header</label>
        <referenceTo>Navigation_Header__c</referenceTo>
        <relationshipLabel>Navigation Pages</relationshipLabel>
        <relationshipName>Navigation_Pages</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Page_URL__c</fullName>
        <description>Short URL for the navigation menu.  This is the field that will control what gets opened when the link is clicked on</description>
        <label>Page URL</label>
        <length>250</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Sort_Order__c</fullName>
        <label>Sort Order</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>css_class__c</fullName>
        <label>css class</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <label>Navigation Page</label>
    <nameField>
        <label>Navigation Page Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Navigation Pages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/dp_clinical_common.cls
public with sharing class dp_clinical_common {
	
  static List<Navigation_Header__c> nav_header = [Select n.Sub_System__c, n.Sort_Order__c, n.Name,  n.Id, (Select css_class__c, Page_URL__c, Nav_Color__c, Name, Image_Name__c, Image_Name_Hover__c, Id, Hyperlink_Target__c, Alt_Page_URL__c From Navigation_Pages__r order by sort_order__c) From Navigation_Header__c n order by sort_order__c];
  static Map<String,List<Navigation_Header__c>> nav_header_map_subsystem;
  static Map<String,Navigation_Header__c> nav_header_map_name; 
  
  static {
  	nav_header_map_subsystem = new map<String,List<Navigation_Header__c>> ();
    nav_header_map_name = new Map<String,Navigation_Header__c>();
    for(Navigation_Header__c header : nav_header) {
      if(nav_header_map_subsystem.get(header.sub_system__c)==null)
        nav_header_map_subsystem.put(header.sub_system__c,new List<Navigation_Header__c> ());
      nav_header_map_subsystem.get(header.sub_system__c).add(header);
      nav_header_map_name.put(header.name,header);
    } 
  }
  
  public hrx_navigation_link getpage_by_name (String pname,Center_Information__c current_center) {
  	hrx_navigation_link nav_page = new hrx_navigation_link([select alt_page_url__c, page_url__c, name from Navigation_Page__c where name = :pname],current_center.use_alternate_url__c,current_center.use_alternate_calendar_url__c);
  	return nav_page;
  }
  
  public List<hrx_navigation_link> getnav_pages_by_subheader(String sname,Center_Information__c center) {
  	List<hrx_navigation_link> nav_links = new List<hrx_navigation_link>();
  	for(Navigation_Header__c nheader : nav_header_map_subsystem.get(sname)) {
  	  for(Navigation_Page__c npage : nheader.navigation_pages__r) {
  	    nav_links.add(new hrx_navigation_link(npage,center.Use_Alternate_url__c,center.Use_Alternate_Calendar_URL__c));
  	  }
  	}
  	return nav_links;
  }
  
  public PageReference pref_to_patient(Center_Information__c current_center, String patient_id) {  	
  	hrx_navigation_link nav_link = new hrx_navigation_link([select alt_page_url__c, page_url__c, name from Navigation_Page__c where name = 'Patient'],current_center.use_alternate_url__c,current_center.use_alternate_calendar_url__c);  	
  	Pagereference pr = new PageReference(nav_link.getpage_url());
  	pr.getParameters().put('ctrid',current_center.id);
  	pr.getParameters().put('ptid',patient_id);
  	pr.setredirect(true);  	      
  	return pr;  	  	
  }
  
  public PageReference pref_navid(Center_Information__c current_center, String navid) {
  	PageReference pr;
  	hrx_navigation_link nav_link = new hrx_navigation_link([select alt_page_url__c, page_url__c, name from Navigation_Page__c where id = :navid],current_center.use_alternate_url__c,current_center.use_alternate_calendar_url__c);
  	pr = new PageReference(nav_link.getpage_url());
  	pr.getParameters().put('ctrid',current_center.id);   
  	pr.setredirect(true); 
  	return pr;
  }
  
  public List<RecentlyViewed> getrecent_records() {
    return [select Id, Name from RecentlyViewed where type = 'Account' order by LastViewedDate desc limit 10];
  }     
  
  public List<Navigation_Page__c> getclinical_header_items() {
    return nav_header_map_name.get('Clinical Header').navigation_pages__r;
  }
  
  public List<hrx_navigation_link> getnav_pages_by_name(String hname,Center_Information__c center) {
  	List<hrx_navigation_link> nav_links = new List<hrx_navigation_link>();
  	for(Navigation_Page__c npage : nav_header_map_name.get(hname).navigation_pages__r) {
  	  nav_links.add(new hrx_navigation_link(npage,center.Use_Alternate_url__c,center.Use_Alternate_Calendar_URL__c));
  	}
  	return nav_links;
  }  
  
  public class hrx_navigation_link {
  	public navigation_page__c nav_page {get;set;}
  	private Boolean alternative_notes;
  	private Boolean alternative_calendar;
  	
  	public hrx_navigation_link(Navigation_Page__c np, Boolean anotes, Boolean acalendar) {
  	  this.nav_page = np;
  	  this.alternative_notes = anotes;
  	  this.alternative_calendar = acalendar;	
  	}
  	
  	public String getpage_url() {
  	  if(nav_page.page_url__c=='/apex/ccare_clinical_calendar')
  	  	return (alternative_calendar?nav_page.Alt_Page_URL__c:nav_page.page_url__c);
      else if(nav_page.name=='Notes')
        return (alternative_notes?nav_page.Alt_Page_URL__c:nav_page.page_url__c);
      else
        return nav_page.page_url__c;
  	} 
  }
}