src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>LeadScore__c</fullName>
        <description>New Calculated Pre-Screen that relies on pre-screen value and census info.</description>
        <formula>/*New Rule - TUPIQ TEST - 2/23/2015 CM */
/*if( ispickval(Contact_Agency__c,&quot;ClearVantage&quot;) || NOT(ISBLANK(Referral_Office__c))  ,&apos;Gold&apos;, 
  if( Center__r.Use_TUPIQ__c,

    if(TransUnion_Score__c&gt;=720 || ((TransUnion_Score__c&lt;650 || isblank(TransUnion_Score__c)) &amp;&amp; (VALUE(Prospect_All_Score__c)&gt;=-1.15 &amp;&amp; VALUE(Prospect_All_Score__c)&lt;0)),&apos;Green&apos;,
      if(TransUnion_Score__c&gt;=650 || ((TransUnion_Score__c&lt;650 || isblank(TransUnion_Score__c)) &amp;&amp; (VALUE(Prospect_All_Score__c)&gt;=-1.45 &amp;&amp; Value(Prospect_All_Score__c)&lt;0)), &apos;Yellow&apos;,
        if(TransUnion_Score__c&gt;=0 || (isblank(TransUnion_Score__c) &amp;&amp; VALUE(Prospect_All_Score__c) &lt; -1.45), &apos;Red&apos;,
          if(isblank(TransUnion_Score__c) &amp;&amp; isblank(Prospect_All_Score__c), &apos;Other&apos;,&apos;Blue&apos;)
        )
      )
    ) 
  ,  	

    if(ISPICKVAL(Pre_Screen__c, &quot;Blue (No Hit)&quot;) &amp;&amp; value(Prospect_IQ_Score__c) &gt;= -2.4 &amp;&amp; !isblank(Prospect_IQ_Score__c),&apos;Green&apos;, 
      if(ISPICKVAL(Pre_Screen__c, &quot;Blue (No Hit)&quot;) &amp;&amp; value(Prospect_IQ_Score__c) &gt;= -2.7 &amp;&amp; !isblank(Prospect_IQ_Score__c),&apos;Yellow&apos;, 
        if(ISPICKVAL(Pre_Screen__c, &quot;Blue (No Hit)&quot;) &amp;&amp; value(Prospect_IQ_Score__c) &lt; -2.7 &amp;&amp; !isblank(Prospect_IQ_Score__c),&apos;Red&apos;,TEXT(Pre_Screen__c))
      )
    )
  )
)*/



/* New Rule - All PIQ - 05/31/2018 */ 
/* if the patient is a referral from a referral partner they are marked Gold regardless of prescreen */
if(ISPICKVAL(Contact_Agency__c,&quot;ClearVantage&quot;) || NOT(ISBLANK(Referral_Office__c)), &apos;Gold&apos;, 
  /* if the record is created after this date then this formula is run */
  if(CreatedDate &gt;= DATETIMEVALUE(&quot;2018-05-31 00:00:00&quot;),
    /* if the prescreen is in this list  the leadscore is set to the prescreen value otherwise the formula is executed to set leadscore */
    if( NOT(CONTAINS(&quot;Green:Yellow:Red:Insufficient Information:PO Box:Website Down-No Prescreen&quot;, TEXT(Pre_Screen__c))),
      /* if the prospect all score is of a certain value, not null and is a blue the leadscore is set as follows */
      if(VALUE(Prospect_All_Score__c) &gt;= -2.3 &amp;&amp; !ISBLANK(Prospect_All_Score__c) &amp;&amp; (TEXT(Pre_Screen__c) = &apos;Blue (No Hit)&apos;),&apos;Green&apos;, 
        if(VALUE(Prospect_All_Score__c) &gt;= -3.05 &amp;&amp; !ISBLANK(Prospect_All_Score__c) &amp;&amp; (TEXT(Pre_Screen__c) = &apos;Blue (No Hit)&apos;),&apos;Yellow&apos;, 
          if(!ISBLANK(Prospect_All_Score__c) &amp;&amp; (TEXT(Pre_Screen__c) = &apos;Blue (No Hit)&apos;),&apos;Red&apos;, &apos;Blue (No Hit)&apos;
          )
        )
      ), TEXT(Pre_Screen__c)
    ), TEXT(Pre_Screen__c)
  ) 
)</formula>
        <label>LeadScore</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pre_Screen_Time__c</fullName>
        <label>Pre Screen Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Pre_Screen__c</fullName>
        <label>Pre Screen</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Checked</fullName>
                </value>
                <value>
                    <fullName>Green</fullName>
                </value>
                <value>
                    <fullName>Yellow</fullName>
                </value>
                <value>
                    <fullName>Red</fullName>
                </value>
                <value>
                    <fullName>Blue (No Hit)</fullName>
                </value>
                <value>
                    <fullName>Website Down-No Prescreen</fullName>
                </value>
                <value>
                    <fullName>PO Box</fullName>
                </value>
                <value>
                    <fullName>Insufficient Information</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>StrikeForce1__USAddress_Address_Status__c</fullName>
        <label>Address Status (Hidden)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Verified</fullName>
                    <default>true</default>
                    <label>Not Verified</label>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CtrlPrescreenColor.cls
// is actually controlling the LeadScore__c color

public with sharing class CtrlPrescreenColor {
	private Lead lead;
  private Id leadId;
  private String prescreen;
  public String leadScore {get; set;}
  public String color {get; private set;}
  public Map<String, String> leadScoreColors {
   get {
       return new Map<String, String> {
           'Green' => 'green',
           'Yellow' => 'yellow',
           'Red' => 'red',
           'Blue (No Hit)' => 'blue',
           'Insufficient Information' => 'dark-gray',
           'Website Down-No Prescreen' => 'black',
           'PO Box' => 'purple',
           'Not Checked' => 'gray'
       };
     }
   set;
  }
  public Boolean prescreenButton {get; private set;}

  public CtrlPrescreenColor(ApexPages.StandardController standardController) {
      this.lead = (Lead)standardController.getRecord();
      leadId = lead.Id;
      Set<String> picklistValues = fetchLeadScoreValues();
      setLeadscore();
      setLeadScoreColor(picklistValues);
      prescreenButton = showPrescreenButton();
  }

  private void setLeadscore() {
    lead = [SELECT Pre_Screen__c, LeadScore__c, Pre_Screen_Time__c,
                   StrikeForce1__USAddress_Address_Status__c
            FROM Lead
            WHERE Id = :leadId];
    prescreen = lead.Pre_Screen__c;
    leadScore = lead.LeadScore__c;
  }

  private Set<String> fetchLeadScoreValues() {
    Set<String> picklistValues = new Set<String>();
		Schema.DescribeFieldResult result = Schema.Lead.Pre_Screen__c.getDescribe();
		List<Schema.PicklistEntry> values = result.getPicklistValues();
		for(Schema.PicklistEntry value : values){
			picklistValues.add(value.getLabel());
		}
    return picklistValues;
  }

  private void setLeadScoreColor(Set<String> picklistValues) {
    String leadScoreColor = leadScore;

    if (picklistValues.Contains(leadScoreColor)) {
      assignColor();
    } else {
      color = 'Not Checked';
    }
  }

  private void assignColor() {
    if(prescreen == 'Website Down-No Prescreen' ||
       prescreen == 'Insufficient Information' ||
       prescreen == 'PO Box') {
      color = leadScoreColors.get(prescreen);
    } else {
      color = leadScoreColors.get(leadScore);
    }
  }

  @TestVisible
  private Boolean showPrescreenButton() {
    Id profileId = UserInfo.getProfileId();
    String userProfileName = [SELECT Name
                              FROM Profile
                              WHERE Id = :profileId
                            ][0].Name;

    String[] authorized = new String[]{};

    if(adminAuthorized()) {
      authorized.add('CC Schedule Admin');
      authorized.add('Call Center Admin');
      authorized.add('System Administrator');
    }

    if(agentsAuthorized()) {
      authorized.add('Call Center Agent');
      authorized.add('Call Center Agent Lead');
      authorized.add('CC Administrator Development Tester');
    }

    if(authorized.contains(userProfileName)) {
      return true;
    }
    return false;
  }

  @TestVisible
  private Boolean adminAuthorized() {
    return lead.StrikeForce1__USAddress_Address_Status__c == 'Verified';
  }

  @TestVisible
  private Boolean agentsAuthorized() {
      return (lead.Pre_Screen__c == null ||
              lead.Pre_Screen__c == 'Not Checked' ||
              lead.Pre_Screen__c == 'Insufficient Information' ||
              lead.Pre_Screen_Time__c < Datetime.now().addDays(-90)) &&
              lead.StrikeForce1__USAddress_Address_Status__c == 'Verified';
  }

  @TestVisible
  public void prescreen() {
    prescreenButton = false;
    ServiceFinancialApiService.prescreen(lead.Id);
    ProspectIqService.run(lead.Id);
  }

  public void updateLeadscore() {
    leadScore = [SELECT LeadScore__c
                 FROM Lead
                 WHERE Id = :leadId].LeadScore__c;
    Set<String> picklistValues = fetchLeadScoreValues();
    setLeadscore();
    setLeadScoreColor(picklistValues);
  }
}