src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>LeadScore__c</fullName>
        <description>New Calculated Pre-Screen that relies on pre-screen value and census info.</description>
        <formula>/*New Rule - TUPIQ TEST - 2/23/2015 CM */
/*if( ispickval(Contact_Agency__c,&quot;ClearVantage&quot;) || NOT(ISBLANK(Referral_Office__c))  ,&apos;Gold&apos;, 
  if( Center__r.Use_TUPIQ__c,

    if(TransUnion_Score__c&gt;=720 || ((TransUnion_Score__c&lt;650 || isblank(TransUnion_Score__c)) &amp;&amp; (VALUE(Prospect_All_Score__c)&gt;=-1.15 &amp;&amp; VALUE(Prospect_All_Score__c)&lt;0)),&apos;Green&apos;,
      if(TransUnion_Score__c&gt;=650 || ((TransUnion_Score__c&lt;650 || isblank(TransUnion_Score__c)) &amp;&amp; (VALUE(Prospect_All_Score__c)&gt;=-1.45 &amp;&amp; Value(Prospect_All_Score__c)&lt;0)), &apos;Yellow&apos;,
        if(TransUnion_Score__c&gt;=0 || (isblank(TransUnion_Score__c) &amp;&amp; VALUE(Prospect_All_Score__c) &lt; -1.45), &apos;Red&apos;,
          if(isblank(TransUnion_Score__c) &amp;&amp; isblank(Prospect_All_Score__c), &apos;Other&apos;,&apos;Blue&apos;)
        )
      )
    ) 
  ,  	

    if(ISPICKVAL(Pre_Screen__c, &quot;Blue (No Hit)&quot;) &amp;&amp; value(Prospect_IQ_Score__c) &gt;= -2.4 &amp;&amp; !isblank(Prospect_IQ_Score__c),&apos;Green&apos;, 
      if(ISPICKVAL(Pre_Screen__c, &quot;Blue (No Hit)&quot;) &amp;&amp; value(Prospect_IQ_Score__c) &gt;= -2.7 &amp;&amp; !isblank(Prospect_IQ_Score__c),&apos;Yellow&apos;, 
        if(ISPICKVAL(Pre_Screen__c, &quot;Blue (No Hit)&quot;) &amp;&amp; value(Prospect_IQ_Score__c) &lt; -2.7 &amp;&amp; !isblank(Prospect_IQ_Score__c),&apos;Red&apos;,TEXT(Pre_Screen__c))
      )
    )
  )
)*/



/* New Rule - All PIQ - 05/31/2018 */ 
/* if the patient is a referral from a referral partner they are marked Gold regardless of prescreen */
if(ISPICKVAL(Contact_Agency__c,&quot;ClearVantage&quot;) || NOT(ISBLANK(Referral_Office__c)), &apos;Gold&apos;, 
  /* if the record is created after this date then this formula is run */
  if(CreatedDate &gt;= DATETIMEVALUE(&quot;2018-05-31 00:00:00&quot;),
    /* if the prescreen is in this list  the leadscore is set to the prescreen value otherwise the formula is executed to set leadscore */
    if( NOT(CONTAINS(&quot;Green:Yellow:Red:Insufficient Information:PO Box:Website Down-No Prescreen&quot;, TEXT(Pre_Screen__c))),
      /* if the prospect all score is of a certain value, not null and is a blue the leadscore is set as follows */
      if(VALUE(Prospect_All_Score__c) &gt;= -2.3 &amp;&amp; !ISBLANK(Prospect_All_Score__c) &amp;&amp; (TEXT(Pre_Screen__c) = &apos;Blue (No Hit)&apos;),&apos;Green&apos;, 
        if(VALUE(Prospect_All_Score__c) &gt;= -3.05 &amp;&amp; !ISBLANK(Prospect_All_Score__c) &amp;&amp; (TEXT(Pre_Screen__c) = &apos;Blue (No Hit)&apos;),&apos;Yellow&apos;, 
          if(!ISBLANK(Prospect_All_Score__c) &amp;&amp; (TEXT(Pre_Screen__c) = &apos;Blue (No Hit)&apos;),&apos;Red&apos;, &apos;Blue (No Hit)&apos;
          )
        )
      ), TEXT(Pre_Screen__c)
    ), TEXT(Pre_Screen__c)
  ) 
)</formula>
        <label>LeadScore</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pre_Screen__c</fullName>
        <label>Pre Screen</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Checked</fullName>
                </value>
                <value>
                    <fullName>Green</fullName>
                </value>
                <value>
                    <fullName>Yellow</fullName>
                </value>
                <value>
                    <fullName>Red</fullName>
                </value>
                <value>
                    <fullName>Blue (No Hit)</fullName>
                </value>
                <value>
                    <fullName>Website Down-No Prescreen</fullName>
                </value>
                <value>
                    <fullName>PO Box</fullName>
                </value>
                <value>
                    <fullName>Insufficient Information</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Prospect_All_Score__c</fullName>
        <label>Prospect All Score</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prospect_All_Tier__c</fullName>
        <label>Prospect All Tier</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StrikeForce1__USAddress_Address_Status__c</fullName>
        <label>Address Status (Hidden)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Verified</fullName>
                    <default>true</default>
                    <label>Not Verified</label>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestCtrlPrescreenColor.cls
@isTest
private class TestCtrlPrescreenColor {
  static Lead lead;
  static PageReference pageReference;
  static CtrlPrescreenColor extension;

  @testSetup static void setup() {
    insert new Lead(
      FirstName = 'Test',
      LastName = 'Patient',
      Street = '123 Main St',
      City = 'Denver',
      State = 'CO',
      PostalCode = '80111',
      Prospect_All_Score__c = '-4.52596639883',
      Prospect_All_Tier__c = 'Tier H'
    );
  }

  private static void init() {
    selectLead();

    pageReference = Page.PreScreenPage;
    pageReference.getParameters().put('id', lead.Id);
    Test.setCurrentPage(pageReference);

    ApexPages.StandardController controller =
                                        new ApexPages.standardController(lead);
    extension = new CtrlPrescreenColor(controller);
  }

  private static void selectLead() {
    lead = [SELECT Id, Pre_Screen__c, LeadScore__c
            FROM Lead
            LIMIT 1
          ];
  }

  static TestMethod void testAssignsColor() {
    selectLead();
    lead.Pre_Screen__c = 'Red';
    update lead;

    init();

    System.assertEquals('Red', lead.Pre_Screen__c);
    System.assertEquals('Red', lead.LeadScore__c);
    System.assertEquals('red', extension.color);
  }

  static TestMethod void testAssignsPoBox() {
    lead = [SELECT Id, Pre_Screen__c, LeadScore__c
            FROM Lead
            LIMIT 1
          ];
    lead.Pre_Screen__c = 'PO Box';
    update lead;

    init();

    System.assertEquals('PO Box', lead.LeadScore__c);
    System.assertEquals('purple', extension.color);
  }

  static TestMethod void testShowPrescreenButton() {
    selectLead();

    lead.StrikeForce1__USAddress_Address_Status__c = 'Verified';
    update lead;

    pageReference = Page.PreScreenPage;
    pageReference.getParameters().put('id', lead.Id);
    Test.setCurrentPage(pageReference);

    ApexPages.StandardController controller =
                                        new ApexPages.standardController(lead);
    extension = new CtrlPrescreenColor(controller);
    Boolean result = extension.showPrescreenButton();

    System.assert(result);
  }

  static TestMethod void testUpdateLeadscore() {
    selectLead();
    lead.Prospect_All_Score__c = '-1.4';
    lead.Prospect_All_Tier__c = '2';
    lead.Pre_Screen__c = 'Green';
    update lead;
    init();
    System.assertEquals('Green', extension.leadScore);

    lead.Pre_Screen__c = 'Red';
    update lead;
    extension.updateLeadscore();
    System.assertEquals('Red', extension.leadScore);
  }
}