src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>LeadScore__c</fullName>
        <description>New Calculated Pre-Screen that relies on pre-screen value and census info.</description>
        <formula>/*New Rule - TUPIQ TEST - 2/23/2015 CM */
/*if( ispickval(Contact_Agency__c,&quot;ClearVantage&quot;) || NOT(ISBLANK(Referral_Office__c))  ,&apos;Gold&apos;, 
  if( Center__r.Use_TUPIQ__c,

    if(TransUnion_Score__c&gt;=720 || ((TransUnion_Score__c&lt;650 || isblank(TransUnion_Score__c)) &amp;&amp; (VALUE(Prospect_All_Score__c)&gt;=-1.15 &amp;&amp; VALUE(Prospect_All_Score__c)&lt;0)),&apos;Green&apos;,
      if(TransUnion_Score__c&gt;=650 || ((TransUnion_Score__c&lt;650 || isblank(TransUnion_Score__c)) &amp;&amp; (VALUE(Prospect_All_Score__c)&gt;=-1.45 &amp;&amp; Value(Prospect_All_Score__c)&lt;0)), &apos;Yellow&apos;,
        if(TransUnion_Score__c&gt;=0 || (isblank(TransUnion_Score__c) &amp;&amp; VALUE(Prospect_All_Score__c) &lt; -1.45), &apos;Red&apos;,
          if(isblank(TransUnion_Score__c) &amp;&amp; isblank(Prospect_All_Score__c), &apos;Other&apos;,&apos;Blue&apos;)
        )
      )
    ) 
  ,  	

    if(ISPICKVAL(Pre_Screen__c, &quot;Blue (No Hit)&quot;) &amp;&amp; value(Prospect_IQ_Score__c) &gt;= -2.4 &amp;&amp; !isblank(Prospect_IQ_Score__c),&apos;Green&apos;, 
      if(ISPICKVAL(Pre_Screen__c, &quot;Blue (No Hit)&quot;) &amp;&amp; value(Prospect_IQ_Score__c) &gt;= -2.7 &amp;&amp; !isblank(Prospect_IQ_Score__c),&apos;Yellow&apos;, 
        if(ISPICKVAL(Pre_Screen__c, &quot;Blue (No Hit)&quot;) &amp;&amp; value(Prospect_IQ_Score__c) &lt; -2.7 &amp;&amp; !isblank(Prospect_IQ_Score__c),&apos;Red&apos;,TEXT(Pre_Screen__c))
      )
    )
  )
)*/



/* New Rule - All PIQ - 05/31/2018 */ 
/* if the patient is a referral from a referral partner they are marked Gold regardless of prescreen */
if(ISPICKVAL(Contact_Agency__c,&quot;ClearVantage&quot;) || NOT(ISBLANK(Referral_Office__c)), &apos;Gold&apos;, 
  /* if the record is created after this date then this formula is run */
  if(CreatedDate &gt;= DATETIMEVALUE(&quot;2018-05-31 00:00:00&quot;),
    /* if the prescreen is in this list  the leadscore is set to the prescreen value otherwise the formula is executed to set leadscore */
    if( NOT(CONTAINS(&quot;Green:Yellow:Red:Insufficient Information:PO Box:Website Down-No Prescreen&quot;, TEXT(Pre_Screen__c))),
      /* if the prospect all score is of a certain value, not null and is a blue the leadscore is set as follows */
      if(VALUE(Prospect_All_Score__c) &gt;= -2.3 &amp;&amp; !ISBLANK(Prospect_All_Score__c) &amp;&amp; (TEXT(Pre_Screen__c) = &apos;Blue (No Hit)&apos;),&apos;Green&apos;, 
        if(VALUE(Prospect_All_Score__c) &gt;= -3.05 &amp;&amp; !ISBLANK(Prospect_All_Score__c) &amp;&amp; (TEXT(Pre_Screen__c) = &apos;Blue (No Hit)&apos;),&apos;Yellow&apos;, 
          if(!ISBLANK(Prospect_All_Score__c) &amp;&amp; (TEXT(Pre_Screen__c) = &apos;Blue (No Hit)&apos;),&apos;Red&apos;, &apos;Blue (No Hit)&apos;
          )
        )
      ), TEXT(Pre_Screen__c)
    ), TEXT(Pre_Screen__c)
  ) 
)</formula>
        <label>LeadScore</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Pre_Screen__c</fullName>
        <label>Pre Screen</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Checked</fullName>
                </value>
                <value>
                    <fullName>Green</fullName>
                </value>
                <value>
                    <fullName>Yellow</fullName>
                </value>
                <value>
                    <fullName>Red</fullName>
                </value>
                <value>
                    <fullName>Blue (No Hit)</fullName>
                </value>
                <value>
                    <fullName>Website Down-No Prescreen</fullName>
                </value>
                <value>
                    <fullName>PO Box</fullName>
                </value>
                <value>
                    <fullName>Insufficient Information</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Prospect_All_Score__c</fullName>
        <label>Prospect All Score</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prospect_All_Tier__c</fullName>
        <label>Prospect All Tier</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LeadBeforeSetsPrescreenDefaultsTest.cls
@isTest
private class LeadBeforeSetsPrescreenDefaultsTest {
  private static Lead lead;

  static void leadInsufficientInformation() {
    insert new Lead(
      FirstName = 'Test',
      LastName = 'Patient',
      Street = null,
      City = 'Denver',
      State = 'CO',
      PostalCode = '80111',
      Prospect_All_Score__c = '-4.52596639883',
      Prospect_All_Tier__c = 'Tier H'
    );
    selectLead();
  }

  static void leadPoBox() {
    insert new Lead(
      FirstName = 'Test',
      LastName = 'Patient',
      Street = 'PO Box 1234',
      City = 'Denver',
      State = 'CO',
      PostalCode = '80111',
      Prospect_All_Score__c = '-4.52596639883',
      Prospect_All_Tier__c = 'Tier H'
    );
    selectLead();
  }

  static void selectLead() {
    lead = [SELECT Id, Pre_Screen__c, LeadScore__c
            FROM Lead
            WHERE Name Like '%Test Patient'
          ];
  }

	@isTest
  static void setPrescreenToInsufficientInformationOnInsertTest() {
    // if any field required to prescreen is null set to Insufficient Information
		leadInsufficientInformation();
    System.assertEquals('Insufficient Information', lead.Pre_Screen__c);
	}

	// @isTest
  // static void setPrescreenToInsufficientInformationOnUpdateTest() {
  //   // if any field required to prescreen is null set to Insufficient Information
	// 	leadPoBox();
  //   System.assertEquals('PO Box', lead.Pre_Screen__c);
  //   lead.Street = null;
  //   update lead;
  //
  //   selectLead();
  //   System.assertEquals('Insufficient Information', lead.Pre_Screen__c);
	// }

  @isTest
  static void setPrescreenToPoBoxOnInsertTest() {
    // if the address contains the letters 'po box' set to 'PO Box'
		leadPoBox();
    System.assertEquals('PO Box', lead.Pre_Screen__c);
	}

  @isTest
  static void setPrescreenToPoBoxOnUpdateTest() {
    // if the address contains the letters 'po box' set to 'PO Box'
		leadInsufficientInformation();
    System.assertEquals('Insufficient Information', lead.Pre_Screen__c);
    lead.Street = 'PO Box 1234';
    update lead;

    selectLead();
    System.assertEquals('PO Box', lead.Pre_Screen__c);
	}
}