src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>Pre_Screen__c</fullName>
        <label>Pre Screen</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Checked</fullName>
                </value>
                <value>
                    <fullName>Green</fullName>
                </value>
                <value>
                    <fullName>Yellow</fullName>
                </value>
                <value>
                    <fullName>Red</fullName>
                </value>
                <value>
                    <fullName>Blue (No Hit)</fullName>
                </value>
                <value>
                    <fullName>Website Down-No Prescreen</fullName>
                </value>
                <value>
                    <fullName>PO Box</fullName>
                </value>
                <value>
                    <fullName>Insufficient Information</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Prescreen_Street_Name__c</fullName>
        <description>Used with StrikeIron and Prescreen</description>
        <label>Prescreen Street Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prospect_All_Score__c</fullName>
        <label>Prospect All Score</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Prospect_All_Tier__c</fullName>
        <label>Prospect All Tier</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StrikeForce1__USAddress_Address_Status__c</fullName>
        <label>Address Status (Hidden)</label>
        <type>Picklist</type>
        <valueSet>
            <valueSetDefinition>
                <value>
                    <fullName>Not Verified</fullName>
                    <default>true</default>
                    <label>Not Verified</label>
                </value>
                <value>
                    <fullName>Verified</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/TestProspectIqService.cls
@isTest
private class TestProspectIqService {
  static Lead lead;

  @testSetup static void setup() {
    Lead lead = new Lead(
      FirstName = 'Test',
      LastName = 'Patient',
      Street = '123 Main St',
      City = 'Denver',
      State = 'CO',
      PostalCode = '80111',
      StrikeForce1__USAddress_Address_Status__c = 'Verified'
    );

    insert lead;
  }

  static void init() {
    lead = [SELECT Id, FirstName, LastName, Street, City,
                   State, PostalCode, Pre_Screen__c,
                   Prescreen_Street_Name__c
            FROM Lead
            LIMIT 1
          ];
  }

  static TestMethod void testProspectIq() {
    init();
    Test.setMock(httpCalloutMock.class, new MockProspectIqServiceResponseGenerator());

    ProspectIqService.run(lead.Id);

    Lead updatedLead = [SELECT Prospect_All_Score__c, Prospect_All_Tier__c
            FROM Lead
            WHERE Id = :lead.Id
          ];

  }
}